FROM ubuntu:20.04

# Enviroment
ENV DEBIAN_FRONTEND noninteractive

ENV GRIDDB_VERSION=5.3.1
ENV GRIDDB_DOWNLOAD_SHA512=d087e79665346f59fe8b9a50b9386f0805bb73da51fd3bc4f97e1737659d5f7676850abb71f7c34a038a0b48227878139f5904ac8bbc95062f4ec39887a75f12

# Install dependency
RUN set -eux \
    && apt-get update -y \
    && apt-get install -y debhelper libtool python3 wget init systemd \
    && apt-get clean all

# Install griddb server
RUN set -eux \
# Download package griddb server
    && wget -q https://github.com/griddb/griddb/releases/download/v${GRIDDB_VERSION}/griddb_${GRIDDB_VERSION}_amd64.deb \
# Check sha512sum package
    && echo "$GRIDDB_DOWNLOAD_SHA512 griddb_${GRIDDB_VERSION}_amd64.deb" | sha512sum --strict --check \
# Install package griddb server
    && dpkg -i griddb_${GRIDDB_VERSION}_amd64.deb \
# Remove package
    && rm griddb_${GRIDDB_VERSION}_amd64.deb
